// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxqvsjuchbkctgzggkqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4cXZzanVjaGJrY3Rnemdna3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzQwMDQsImV4cCI6MjA1ODI1MDAwNH0.Rau-vJ7gitltixWt1hNzjHsVExvetUb3YdZ3Kwa6ifs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);